language: ruby

sudo: false

services:
  - docker

env:
  global:
    - CC_TEST_REPORTER_ID=9f7f740ac1b6e264e1189fa07a6687a87bcdb9f3c0f4199d4344ab3b538e187e
    - KAFKA_HEAP_OPTS="-Xmx512m -Xms512m"

rvm:
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem update --system

before_script:
  - docker-compose up -d
  - cd ext && bundle exec rake && cd ..
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec

after_script:
  - docker-compose stop
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
