version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    # When bumping this also bump fallback in spec_helper.rb:12
    image: "wurstmeister/kafka:2.12-2.2.1"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
      KAFKA_CREATE_TOPICS: "consume_test_topic:3:1,empty_test_topic:3:1,load_test_topic:3:1,produce_test_topic:3:1,rake_test_topic:3:1,watermarks_test_topic:3:1"
