version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    environment:
      JAVA_OPTS: "-Xms1g -Xmx1g"
  kafka:
    image: wurstmeister/kafka:1.0.1
    ports:
      - "9092:9092"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    environment:
      JAVA_OPTS: "-Xms1g -Xmx1g"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "consume_test_topic:3:1,empty_test_topic:3:1,load_test_topic:3:1,produce_test_topic:3:1,rake_test_topic:3:1,watermarks_test_topic:3:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
